"""add Questionnaire model

Revision ID: a74a05a6eeac
Revises: c5f5b12199c4
Create Date: 2024-03-14 17:56:48.620310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a74a05a6eeac'
down_revision: Union[str, None] = 'c5f5b12199c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('questionnaires_name_key', 'questionnaires', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('questionnaires_name_key', 'questionnaires', ['name'])
    # ### end Alembic commands ###
