"""add author field in Article

Revision ID: c5cac85b9be0
Revises: a74a05a6eeac
Create Date: 2024-03-15 14:28:45.246060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5cac85b9be0'
down_revision: Union[str, None] = 'a74a05a6eeac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('author', sa.String(), nullable=False))
    op.alter_column('comments', 'web_site',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'web_site',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('articles', 'author')
    # ### end Alembic commands ###
