"""add author field in 

Revision ID: f98bb5f2706a
Revises: fea6c0ed1b58
Create Date: 2024-03-19 12:39:05.808577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f98bb5f2706a'
down_revision: Union[str, None] = 'fea6c0ed1b58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_products_order_id_fkey', 'order_products', type_='foreignkey')
    op.drop_constraint('order_products_product_id_fkey', 'order_products', type_='foreignkey')
    op.create_foreign_key(None, 'order_products', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'order_products', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('product_ingredient_ingredient_id_fkey', 'product_ingredient', type_='foreignkey')
    op.drop_constraint('product_ingredient_product_id_fkey', 'product_ingredient', type_='foreignkey')
    op.create_foreign_key(None, 'product_ingredient', 'ingredients', ['ingredient_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'product_ingredient', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('supplements_product_id_fkey', 'supplements', type_='foreignkey')
    op.create_foreign_key(None, 'supplements', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'supplements', type_='foreignkey')
    op.create_foreign_key('supplements_product_id_fkey', 'supplements', 'products', ['product_id'], ['id'])
    op.drop_constraint(None, 'product_ingredient', type_='foreignkey')
    op.drop_constraint(None, 'product_ingredient', type_='foreignkey')
    op.create_foreign_key('product_ingredient_product_id_fkey', 'product_ingredient', 'products', ['product_id'], ['id'])
    op.create_foreign_key('product_ingredient_ingredient_id_fkey', 'product_ingredient', 'ingredients', ['ingredient_id'], ['id'])
    op.drop_constraint(None, 'order_products', type_='foreignkey')
    op.drop_constraint(None, 'order_products', type_='foreignkey')
    op.create_foreign_key('order_products_product_id_fkey', 'order_products', 'products', ['product_id'], ['id'])
    op.create_foreign_key('order_products_order_id_fkey', 'order_products', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###
