"""add author field in 

Revision ID: fea6c0ed1b58
Revises: 91673903e59b
Create Date: 2024-03-19 12:32:41.557027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fea6c0ed1b58'
down_revision: Union[str, None] = '91673903e59b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_supplements_supplement_id_fkey', 'order_supplements', type_='foreignkey')
    op.drop_constraint('order_supplements_order_id_fkey', 'order_supplements', type_='foreignkey')
    op.create_foreign_key(None, 'order_supplements', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'order_supplements', 'supplements', ['supplement_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_supplements', type_='foreignkey')
    op.drop_constraint(None, 'order_supplements', type_='foreignkey')
    op.create_foreign_key('order_supplements_order_id_fkey', 'order_supplements', 'orders', ['order_id'], ['id'])
    op.create_foreign_key('order_supplements_supplement_id_fkey', 'order_supplements', 'supplements', ['supplement_id'], ['id'])
    # ### end Alembic commands ###
